<?php
require "./header.php";


$city_select = isset($_COOKIE['city'])?$_COOKIE['city']:0;
$city_select = isset($_SESSION['city'])?$_SESSION['city']:$city_select;

if($_SERVER['REQUEST_METHOD'] == "POST"){
	$city_select = (isset($_POST['city']))?sum_check_box($_POST['city']):0;
	if($city_select == 0)
	{
		$_SESSION['message'] = "Select at least one city";
	}else{
		$_SESSION['city'] = $city_select;
		redirect('./listing-search.php');
	}
	
}


?>


<!--Image Map Generated by http://www.image-map.net/  -->

<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td align="center">
            <img src="./images/durhamregionmap.jpeg" usemap="#image-map">
        </td>
    </tr>
</table>


<!--<img align="centre" src="./images/durhamregionmap.jpeg" usemap="#image-map"> -->

<map name="image-map">
    <area target="" alt="Pickering" title="Pickering" href="./listing-search.php?city=16" coords="132,465,129" shape="circle">
    <area target="" alt="Ajax" title="Ajax" href="./listing-search.php?city=1" coords="350,412,83" shape="circle">
    <area target="" alt="Whitby" title="Whitby" href="./listing-search.php?city=64" coords="498,303,95" shape="circle">
    <area target="" alt="Oshawa" title="Oshawa" href="./listing-search.php?city=8" coords="683,301,89" shape="circle">
    <area target="" alt="Bowmanville" title="Bowmanville" href="./listing-search.php?city=16" coords="980,232,119" shape="circle">
    <area target="" alt="Brooklin" title="Brooklin" href="./listing-search.php?city=2" coords="405,105,121" shape="circle">
    <area target="" alt="Port perry" title="Port perry" href="./listing-search.php?city=32" coords="676,85,122" shape="circle">
</map>

<form method="post" action="<?php echo $_SERVER['PHP_SELF'];  ?>">
<table  width="100%" border="0" cellspacing="0" cellpadding="0">
  				<tr align="center">
  					<td align="right">Location:</td>
  					<td align="left"><br /><?php echo build_checkbox('city');?>
                        

                    </td>
  				</tr>
				 <tr>
					<td align="right">
						<input type="submit" value="search"/>
					</td>
				</tr>
</table



<?php require "./footer.php"; ?>